language: node_js
sudo: false
node_js:
- '0.12'
git:
  submodules: false
branches:
  only:
    - layout
cache:
  directories:
  - node_modules
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && git fetch && git checkout layout || true'
install:
- npm install
- npm prune
script: npm run build
after_script:
- bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/ruuvi/ruuvi.github.io.git
  - secure: b+Z4bvd731kAYgedyntMxydNEx+MJHfAQ/w96NutwScAUdjJG3YjDlDamo8Bb4yKQa6waifmAJsPYwZd5qpgFAuWdGLBhZaxxG9bFu/XfJTB3ktuvbreAsWV778uaUesXNsi6vYRv9FGqne30KeeyEcjZipm+FmxZuhCKQSFR4TamdIpxAvoH8IbQhbKyOK3vEGbMyqqOiNLnqcqAQzWcGl7b9xuclbC6q7x2R6Cnc0WtgvZgqj0gYG/9KyclWCNd4l5yZ+lMfcUp/1LzYZULnXyijm9xg2buY/X4uaUtxqXdvD3c5Ls9HIEdWmnlZcb1S3dF1RVavDTIYpAUC0pc6EAv4z9pb4r0iiATurwx/wyw6m14FIAlUWz0b+stujaTcomgYtHakeJWbfMSn83/MmfVsZYvJfTGr1lRzARJx4zXrkd13eiBwZ2WtG3doulSMQ0YRPn9lrkViSKaA4Hw6rVhSBR6O36QngAznRBfg+2OjoaC5hTecyKMYhReH0ILQMAGScn0/S8J561BCYmSVlXDC7m57mvMUx+EZfmhf6mHqx6Uh5jC59/a02UO3U1ptGqxxILIX4p5DX4aiiQW0AnNn0bDTrd7+OsZJMZ/KjNqvItKlXoES2nvONXTRKtybEQmwr9rsVLNr4mfx+/QVVhuazMah42fHR57ZUaX2s=
