language: node_js
sudo: false
node_js:
- '0.12'
git:
  submodules: false
cache:
  directories:
  - node_modules
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && git fetch && git checkout layout || true'
install:
- npm install
- npm prune
script: npm run build
after_script:
- bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/ruuvi/ruuvi.github.io.git
  - secure: oQuMQGmJMx0PwL4lsCuK5gy4RbT91wi2v6jefCf0FWRlKoqxR16QYFYknwMfhpGOdmFMrU83xayJdyGiTKGr7A2UUBR3i0nuUmmy6gcmi/o/Y9D8G5gNsOCpQ6BXJCQkve5Qw16USTDDmbPCAQA+f8BDtnTz48F8aaKHghIjwZchOAAxoC+0lIuArvwBchx/GZWryZKLu7T2zXxThdbOa4SCTRSvxbjojRsnGYk/3wuKAriSG3vU47+EtAn8pegxwSpMuifWD3Lkpc9Xmh1F7whaSvvE4R5wuhfigPL/49tYiFvZpiQiE89miic+s2CMqvrOaRG48mRVtEAhW0JofxW4Nb+5or0nVzhX+FcaIogkJEcePPvKXROF4mJfIS+o5Sl1+imu3HRX0SNzvt9tCP4UL8OT/OPLlDmKHGsAbDrB/g5NFKuLyGVkaaR/w7+PZqvqqffGLAtZBL3E+okVfks3xWLfwN+5BcjEZMSQYHqsld1Z95Phb0q8NKn0/So3Un2sLjUVVKFaL5PyR53kmF1kE+k57PnTmsoTK8muCF/smO7fD75QxMOFOBITwdd2TdpZYTTEerY5VJPqXdmRf2d1X/7AMp8hfw3Byr4AN4sN1j998gpm0imrIO4BHiWEO/9fLmNwXEFhKuoiIRYW/zOA0c6cFZ5ZzllowQi7RhY=
